<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <Configurations>Debug;Release;Ad-Hoc;AppStore</Configurations>
    <Platforms>iPhoneSimulator;iPhone;AnyCPU</Platforms>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
    <ConsolePause>false</ConsolePause>
    <CodesignKey>iPhone Developer</CodesignKey>
    <DebugType>full</DebugType>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
    <CreatePackage>false</CreatePackage>
    <CodesignProvision>Automatic</CodesignProvision>
    <DeviceSpecificBuild>false</DeviceSpecificBuild>
    <MtouchDebug>true</MtouchDebug>
    <MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
    <IOSDebuggerPort>10001</IOSDebuggerPort>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhoneSimulator' ">
    <ConsolePause>false</ConsolePause>
    <CodesignKey>iPhone Developer</CodesignKey>
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">
    <ConsolePause>false</ConsolePause>
    <CodesignKey>iPhone Developer</CodesignKey>
    <IpaPackageName>
    </IpaPackageName>
    <DebugType>full</DebugType>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
    <CreatePackage>false</CreatePackage>
    <DeviceSpecificBuild>false</DeviceSpecificBuild>
    <MtouchDebug>true</MtouchDebug>
    <MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
    <IOSDebuggerPort>10001</IOSDebuggerPort>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
    <ConsolePause>false</ConsolePause>
    <CodesignKey>iPhone Developer</CodesignKey>
    <DebugSymbols>true</DebugSymbols>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Ad-Hoc|iPhone' ">
    <ConsolePause>false</ConsolePause>
    <BuildIpa>true</BuildIpa>
    <CodesignProvision>Automatic:AdHoc</CodesignProvision>
    <CodesignKey>iPhone Distribution</CodesignKey>
    <DebugSymbols>true</DebugSymbols>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'AppStore|iPhone' ">
    <CodesignKey>iPhone Distribution</CodesignKey>
    <ConsolePause>false</ConsolePause>
    <CodesignProvision>Automatic:AppStore</CodesignProvision>
    <DebugSymbols>true</DebugSymbols>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Ad-Hoc|AnyCPU' ">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'AppStore|AnyCPU' ">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Ad-Hoc|iPhoneSimulator' ">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'AppStore|iPhoneSimulator' ">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Documents\sample.pdf" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Library\mTouchPDFReaderLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="7.0.1" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="7.0.2" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Condition="'$(_ResourcePrefix)' != ''" Update="Resources\Icon-76%402x.png">
      <Link>Resources\Icon-76%402x.png</Link>
    </BundleResource>
    <BundleResource Condition="'$(_ResourcePrefix)' != ''" Update="Resources\Icon-72%402x.png">
      <Link>Resources\Icon-72%402x.png</Link>
    </BundleResource>
    <BundleResource Condition="'$(_ResourcePrefix)' != ''" Update="Resources\Icon-60%402x.png">
      <Link>Resources\Icon-60%402x.png</Link>
    </BundleResource>
    <BundleResource Condition="'$(_ResourcePrefix)' != ''" Update="Resources\Icon%402x.png">
      <Link>Resources\Icon%402x.png</Link>
    </BundleResource>
    <BundleResource Condition="'$(_ResourcePrefix)' != ''" Update="Resources\documents%402x.png">
      <Link>Resources\documents%402x.png</Link>
    </BundleResource>
    <BundleResource Condition="'$(_ResourcePrefix)' != ''" Update="Resources\documents%403x.png">
      <Link>Resources\documents%403x.png</Link>
    </BundleResource>
    <BundleResource Condition="'$(_ResourcePrefix)' != ''" Update="Resources\settings%402x.png">
      <Link>Resources\settings%402x.png</Link>
    </BundleResource>
    <BundleResource Condition="'$(_ResourcePrefix)' != ''" Update="Resources\settings%403x.png">
      <Link>Resources\settings%403x.png</Link>
    </BundleResource>
  </ItemGroup>
</Project>